### PR TITLE
modulesync 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Still lists Puppet 4 support (but not Puppet 6) and it's failing to install Ruby 2.1.

**Comment by b4ldr** [comment]
I have updated metadata.json can this get rebased (couldn't see an obvious way to do it my self without merging as well)

**Comment by ekohl** [comment]
I think you should be able to force push it since you are a member. Before I do so, please try it to see if that works.

**Comment by b4ldr** [comment]
> I think you should be able to force push it since you are a member. Before I do so, please try it to see if that works.

yes that worked thanks

**Review by ekohl — APPROVED** [review]

**Pull request merged**
